server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: neo_route
          uri: http://www.ityouknow.com
          predicates:
            - Path=/foo/{segment}
            - Cookie=sessionId, 123456
            - Header=X-Request-Id, \d+
            - Method=POST
            - Query=keep, pu.
            - RemoteAddr=192.168.1.1/24
            - Before=2020-01-20T06:06:06+08:00[Asia/Shanghai]
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug