server:
  port: 8888

spring:
  application:
    name: gateway-service-zuul
zuul:
  routes:
    #zuul.routes.baidu.path=/bai/**
    #zuul.routes.baidu.url=http://www.baidu.com/
    api-nine:
      path: /producer/**
      service-id: nine-producer
  retryable: true
ribbon:
  MaxAutoRetries: 2   #对当前服务的重试次数
  MaxAutoRetriesNextServer: 0  #切换相同Server的次数

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/